# Book settings
title: Synchrotron IR-THz Nanospectroscopy Knowledge Hub
author: Raul Freitas and Ferenc Borondics
copyright: "2025"
logo: logo.png

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath

execute:
  allow_errors: false
  timeout: 1000

html:
  navbar_number_sections: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  comments:
    hypothesis: true
    code_folding: true
    code_toggle: true

  css_files:
    - _static/custom.css

sphinx:
  config:
    html_show_source: false
    code_prompt_show: "Mostrar código"
    code_prompt_hide: "Ocultar código"
    html_js_files:
      - https://unpkg.com/thebe@latest/lib/thebe.min.js
    html_static_path: ['_static']
    numfig: true
    numfig_secnum_depth: 2
    use_image_zoom: true
  extra_extensions:
    - sphinx_togglebutton
    - sphinx_proof
    - bibtex_reference_style: label



launch_buttons:
  notebook_interface: jupyterlab
  thebe: true
  binderhub_url: "https://mybinder.org"

repository:
  url: https://github.com/raul-freitas/sr-ir-thz-knowledge-hub
  branch: main

bibtex_bibfiles:
  - references.bib
  - references_.bib

latex:
  latex_engine: pdflatex
  latex_documents:
    extra_packages:
      - booktabs

  